#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Set env vars for firebird
agent.set_env("FIREBIRD_PORT",data.get("port",3050))
agent.set_env("FIREBIRD_DATABASE_DEFAULT_CHARSET",data.get("charset","ISO-8859-2"))
agent.set_env("FIREBIRD_TIMEZONE",data.get("tz","Europe/Budapest"))
agent.set_env("FIREBIRD_FIREWALL",data.get("ff","True"))
