#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

ff = os.getenv("FIREBIRD_FIREWALL") == "True"

if ff:
  agent.remove_public_service(os.environ['MODULE_ID'])
else:
  agent.add_public_service(os.environ['MODULE_ID'], [
    os.environ['FIREBIRD_PORT']+"/tcp", # Firebird port
  ], replace_ports=True)
