#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

agent.add_public_service(os.environ['MODULE_ID'], [
    "3050/tcp", # Standard port for Firebird client connections.
])

# Ignore exit code
