#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}


# Read current configuration from the environment file
config["charset"] = os.getenv("FIREBIRD_DATABASE_DEFAULT_CHARSET","")
config["port"] = os.getenv("FIREBIRD_PORT","")
config["ff"] = os.getenv("FIREBIRD_FIREWALL","False") == "True";
config["tz"] = os.getenv("FIREBIRD_TIMEZONE","")

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
