#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}


# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
#config["tcp_port_firebird"] = os.getenv("TCP_PORT_FIREBIRD")
config["charset"] = os.getenv("FIREBIRD_DATABASE_DEFAULT_CHARSET")
#config["port"] = os.getenv("TCP_PORT_FIREBIRD")
config["tz"] = os.getenv("TZ")

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
