#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "port": renv["FIREBIRD_PORT"],
    "charset": renv["FIREBIRD_DATABASE_DEFAULT_CHARSET"],
    "tz": renv["FIREBIRD_TIMEZONE"],
    "ff": renv["FIREBIRD_FIREWALL"] == "True",
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
